version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run
      executor: cypress/browsers-chrome69
         command: npx cypress-tags run -e TAGS='@idmngmt' --env configFile=dev --browser chrome
      