version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0   
workflows:
  build:
    jobs:
      - cypress/run:
          no-workspace: true
          executor: cypress/browsers-chrome69
          command: npx cypress-tags run -e TAGS='@forgotpass' --env configFile=prod
          post-steps:
            - store_artifacts:
                path: /root/project/cypress/output
            - store_artifacts:
                path: /root/project/cypress/test-results/cucumber-json
            - store_test_results:
                path: /root/project/cypress/target/site/serenity
                prefix: test