version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
commands:
  create-report:
    steps:
       - run: node cypress/support/reporter.js
workflows:
  build:
    jobs:
      - cypress/run:
          no-workspace: true
          executor: cypress/browsers-chrome69
          command: npx cypress-tags run -e TAGS='@aw' --env configFile=prod --browser chrome
      - my-job:
        steps:
            - create-report 
            - store_artifacts:
                path: /root/project/cypress/output
            - store_artifacts:
                path: /root/project/cypress/test-results/cucumber-json
            - store_test_results:
                path: /root/project/cypress/test-results/cucumber-json
                prefix: test