version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          no-workspace: true
          executor: cypress/browsers-chrome69
          command: npx cypress-tags run -e TAGS='@forgotpass' --env configFile=dev --browser chrome
          post-steps:
            - run: node cypress/support/reporter.js
            - store_artifacts:
                path: /root/project/cypress/output
            - store_artifacts:
                path: /root/project/cypress/test-results/cucumber-json
                 prefix: tests
            - store_test_results:
                path: /root/project/cypress/test-results
                
