jobs:
  build:
    docker:
      - image: cypress/browsers:chrome69
    steps:
      - slack/notify:
          color: '#42e2f4'
          message: This is a custom message notification
          webhook: 'https://hooks.slack.com/services/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'
orbs:
  slack: circleci/slack@3.3.0
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build